### PR TITLE
Apps Bluetooth support & 1.0 breaking changes

### LINKED ISSUE #20: [Bluetooth] Control over page reload hack
There's a page reload workaround in chooseDevice that's a real hack.

https://github.com/microbit-foundation/microbit-connection/blob/c01107d291ead6aa9cf387427df0cc8d88192d56/lib/bluetooth.ts#L336

Ideally we'd determine if still necessary and make it an option the calling code has to be aware of.

### LINKED ISSUE #57: Can not connect to micro:bit in Brave browser due to USB serial anti-fingerprinting
## Bug Description

Can not connect to microbit.

## How To Reproduce

1. https://python.microbit.org/v/3/project
2. Open new project (demo code is fine)
3. Connect microbit
4. Send the code to microbit
5. Try to pair the microbit (seen in the list)
6. Get error: WebUSB error : Please reconnect your micro:bit and try again.

## Expected behavior

Be able to download code to microbit.. FWIW, I can connect to the same device with https://makecode.microbit.org/#editor. I'm only trying one editor at a time.

## Environment

- OS: Linux Mint 21
- Browser chome (brave)
- Version  1.67.116 Chromium: 126.0.6478.71 (Official Build) (64-bit)

## screenshots

Screenshot_2024-07-09_20-45-25
Screenshot_2024-07-09_20-46-53

## Additional context

My microbit:
```
# DAPLink Firmware - see https://daplink.io
Build ID: v0257-gc782a5ba (gcc)
Unique ID: 99063602000528207dbe0e669db29888000000006e052820
HIC ID: 6e052820
Auto Reset: 1
Automation allowed: 0
Overflow detection: 0
Incompatible image detection: 1
Page erasing: 0
Daplink Mode: Interface
Interface Version: 0257
Bootloader Version: 0257
Git SHA: c782a5ba907377658bc28aa8d132a0fa44543687
Local Mods: 0
USB Interfaces: MSD, CDC, HID, WebUSB
Bootloader CRC: 0x725bea7d
Interface CRC: 0xe561f1de
Remount count: 0
URL: https://microbit.org/device/?id=9906&v=0257
```

Developer console in browser shows this:

```
board-serial-info.ts:20 USB serial number unexpected length: 16
webusb.ts:134 An error occurred whilst attempting to use WebUSB.
webusb.ts:134 Details of the error can be found below, and may be useful when trying to replicate and debug the error.
webusb.ts:134 Error: Could not recognise the Board ID b
    at new cl (board-id.ts:16:13)
    at cl.parse (board-id.ts:56:12)
    at oA.parse (board-serial-info.ts:25:40)
    at get boardSerialInfo (dap-wrapper.ts:63:28)
    at uSe.reconnectAsync (dap-wrapper.ts:89:29)
    at async mSe.connectInternal (webusb.ts:386:5)
    at async webusb.ts:170:13
    at async mSe.withEnrichedErrors (webusb.ts:318:14)
    at async GLe.connectInternal (project-actions.tsx:192:13)
    at async GLe.flash (project-actions.tsx:508:25)
    at async SendButton.tsx:61:15
webusb.ts:134 Device status NOT_CONNECTED
webusb.ts:301 Disconnection complete
```

### LINKED ISSUE #71: Consider aligning post-flash connection state between USB and Bluetooth in microbit-connection

### PR DESCRIPTION
**Pull request by microbit-matt-hillsdon**
This contains breaking changes (e.g. flash progress interface, connect
signature, device error codes) and will form part of a v1.0.0 after a few
beta releases. Detailed notes on changes can be found in MIGRATATION.md.

Migrating USB-only code requires minor tweaks only.

Highlights:
- Switch to capacitor-ble for bluetooth (including on web)
- Support DFU and partial flashing on iOS/Android platforms (for Capacitor Android/iOS apps)
- Add BLE APIs for missing services
- Add Capacitor app and a web based app to help with testing USB
- Drop a bunch of workarounds that testing suggest no longer apply

Fixes #20
Fixes #57
Fixes #71

### CODE REVIEW

File: packages/microbit-connection/src/bluetooth/flashing/flashing-full.ts [hunk 1]
```diff
@@ -0,0 +1,119 @@
...
+ *
+ * @throws {DeviceError} On flash failure.
+ */
+export async function fullFlash(
+  connection: BluetoothDeviceWrapper,
+  boardVersion: BoardVersion,
+  memoryMap: MemoryMap,
+  progress: ProgressCallback,
+): Promise<void> {
+  connection.log("Full flash");
```
Comment (microbit-matt-hillsdon) [inline packages/microbit-connection/src/bluetooth/flashing/flashing-full.ts:31]: These need to use logging throughout.

File: lib/flashing/nordic-dfu.ts [hunk 2]
```diff
@@ -0,0 +1,270 @@
+import { BleDevice } from "@capacitor-community/bluetooth-le";
+import { Capacitor, PluginListenerHandle } from "@capacitor/core";
+import { Directory, Filesystem, WriteFileOptions } from "@capacitor/filesystem";
+import { DfuState, NordicDfu } from "@microbit/capacitor-community-nordic-dfu";
+import JSZip from "jszip";
```
Comment (microbit-matt-hillsdon) [inline lib/flashing/nordic-dfu.ts]: I wonder if we can replace this dependency. Do we even need compression in our ZIPs?

File: packages/microbit-connection/src/flashing/nordic-dfu.ts [hunk 3]
```diff
@@ -0,0 +1,270 @@
...
+  //    uint8_t  magic[12];                 // identify this struct "microbit_app"
+  //    uint32_t version;                   // version of this struct == 1
+  //    uint32_t app_size;                  // only used for DFU_FW_TYPE_APPLICATION
+  //    uint32_t hash_size;                 // 32 => DFU_HASH_TYPE_SHA256 or zero to bypass hash check
+  //    uint8_t  hash_bytes[32];            // hash of whole DFU download
+  //} microbit_dfu_app_t;
+  const appSize = appBin.length;
+  const magic = "microbit_app";
+  const version = 1;
+  const hashSize = 0;
```
Comment (microbit-matt-hillsdon) [inline packages/microbit-connection/src/flashing/nordic-dfu.ts]: This is what the Android app does, but is rubbish. Let's open an issue to track. Perhaps it's the same hash as above? Either way likely easy fix and can just try it out.

File: tsconfig.json [hunk 4]
```diff
@@ -14,6 +14,8 @@
     /* Linting */
     "strict": true,
     "noUnusedLocals": true,
+    /* For jszip, can we replace it? */
+    "allowSyntheticDefaultImports": true,
```
Comment (microbit-matt-hillsdon) [inline tsconfig.json]: See note above about replacing js-zip.

File: .github/workflows/build-docs.yml [hunk 5]
```diff
@@ -15,16 +15,20 @@ jobs:
...
-        run: npm run docs
+        run: npm run docs -w @microbit/microbit-connection
       - name: Upload artifact
         uses: actions/upload-pages-artifact@v3
         with:
-          path: ./docs/build
+          path: ./packages/microbit-connection/docs/build
 
   deploy:
-    if: ${{ startsWith(github.ref, 'refs/tags/') }}
```
Comment (microbit-grace) [inline .github/workflows/build-docs.yml:27]: One-off hack for preventing docs from deploying when releasing apps that probably requires reverting.

File: AGENTS.md [hunk 6]
```diff
@@ -0,0 +1,65 @@
+# microbit-connection
+
+TypeScript library for connecting to BBC micro:bit devices via USB and Bluetooth (BLE), including partial and full (DFU) flashing. Published as `@microbit/microbit-connection` on NPM. This branch is based off the "apps" branch where we've added Capacitor support for use in a mobile app and are making various other breaking changes that will end up as a v1.0.0 when the app is stable.
```
Comment (microbit-grace) [inline AGENTS.md]: This might need updating to not refer to the "apps" branch, once this is merged in.

File: .github/workflows/build.yml [hunk 7]
```diff
@@ -15,15 +15,17 @@ jobs:
...
           cache: npm
       - uses: microbit-foundation/npm-package-versioner-action@v1
+        with:
+          working-directory: packages/microbit-connection
       - run: npm ci
         env:
           NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       - run: npm run ci
-      - run: npm publish
+      - run: npm publish -w @microbit/microbit-connection --tag apps
```
Comment (microbit-grace) [inline .github/workflows/build.yml]: Remove "apps" tag?

File: AGENTS.md (hunk 6 above)
Comment (microbit-matt-hillsdon) [reply AGENTS.md]: Removed in 34209073b764fd5c7be1f0c404931e3f79c556b7
